#!/usr/bin/env python3
"""
CSV to DBC Converter for WoW 3.3.5a (WotLK)
Converts CSV files to binary .dbc format and merges with existing DBCs

This tool reads existing WotLK .dbc files and updates them with new entries
from CSV files generated by DB2_to_DBC.py or DB2_to_DBC_Filtered.py
"""

import os
import sys
import csv
import struct
from pathlib import Path
from collections import defaultdict
from typing import Dict, List, Tuple, Any, Optional

# Configuration
DBC_DIR = "6_DBC_Binary/DBFilesClient"
CSV_SOURCES = ["2_DBCRetail_to_Wotlk_csv", "3_DBC_Filtered"]

# DBC Magic Header
DBC_MAGIC = b'WDBC'

# Field type constants
TYPE_INT = 'int32'
TYPE_UINT = 'uint32'
TYPE_FLOAT = 'float'
TYPE_STRING = 'string'
TYPE_LOCSTRING = 'locstring'  # 16 locale strings + flags


class DBCSchema:
    """Schema definition for DBC tables"""
    
    # Schema format: (field_name, field_type)
    # Schemas are ordered alphabetically for easy maintenance
    SCHEMAS = {
        # ========================================
        # C
        # ========================================
        'CreatureDisplayInfo': [
            ('ID', TYPE_UINT),
            ('ModelID', TYPE_UINT),
            ('SoundID', TYPE_UINT),
            ('ExtendedDisplayInfoID', TYPE_UINT),
            ('CreatureModelScale', TYPE_FLOAT),
            ('CreatureModelAlpha', TYPE_UINT),
            ('TextureVariation_1', TYPE_STRING),
            ('TextureVariation_2', TYPE_STRING),
            ('TextureVariation_3', TYPE_STRING),
            ('PortraitTextureName', TYPE_STRING),
            ('BloodLevel', TYPE_INT),
            ('BloodID', TYPE_UINT),
            ('NPCSoundID', TYPE_UINT),
            ('ParticleColorID', TYPE_UINT),
            ('CreatureGeosetData', TYPE_UINT),
            ('ObjectEffectPackageID', TYPE_UINT),
        ],
        
        'CreatureModelData': [
            ('ID', TYPE_UINT),
            ('Flags', TYPE_UINT),
            ('ModelName', TYPE_STRING),
            ('SizeClass', TYPE_UINT),
            ('ModelScale', TYPE_FLOAT),
            ('BloodID', TYPE_UINT),
            ('FootprintTextureID', TYPE_UINT),
            ('FootprintTextureLength', TYPE_FLOAT),
            ('FootprintTextureWidth', TYPE_FLOAT),
            ('FootprintParticleScale', TYPE_FLOAT),
            ('FoleyMaterialID', TYPE_UINT),
            ('FootstepShakeSize', TYPE_UINT),
            ('DeathThudShakeSize', TYPE_UINT),
            ('SoundID', TYPE_UINT),
            ('CollisionWidth', TYPE_FLOAT),
            ('CollisionHeight', TYPE_FLOAT),
            ('MountHeight', TYPE_FLOAT),
            ('GeoBoxMinX', TYPE_FLOAT),
            ('GeoBoxMinY', TYPE_FLOAT),
            ('GeoBoxMinZ', TYPE_FLOAT),
            ('GeoBoxMaxX', TYPE_FLOAT),
            ('GeoBoxMaxY', TYPE_FLOAT),
            ('GeoBoxMaxZ', TYPE_FLOAT),
            ('WorldEffectScale', TYPE_FLOAT),
            ('AttachedEffectScale', TYPE_FLOAT),
            ('MissileCollisionRadius', TYPE_FLOAT),
            ('MissileCollisionPush', TYPE_FLOAT),
            ('MissileCollisionRaise', TYPE_FLOAT),
        ],
        
        'CreatureSoundData': [
            ('ID', TYPE_UINT),
            ('SoundExertionID', TYPE_UINT),
            ('SoundExertionCriticalID', TYPE_UINT),
            ('SoundInjuryID', TYPE_UINT),
            ('SoundInjuryCriticalID', TYPE_UINT),
            ('SoundInjuryCrushingBlowID', TYPE_UINT),
            ('SoundDeathID', TYPE_UINT),
            ('SoundStunID', TYPE_UINT),
            ('SoundStandID', TYPE_UINT),
            ('SoundFootstepID', TYPE_UINT),
            ('SoundAggroID', TYPE_UINT),
            ('SoundWingFlapID', TYPE_UINT),
            ('SoundWingGlideID', TYPE_UINT),
            ('SoundAlertID', TYPE_UINT),
            ('SoundFidget_1', TYPE_UINT),
            ('SoundFidget_2', TYPE_UINT),
            ('SoundFidget_3', TYPE_UINT),
            ('SoundFidget_4', TYPE_UINT),
            ('SoundFidget_5', TYPE_UINT),
            ('CustomAttack_1', TYPE_UINT),
            ('CustomAttack_2', TYPE_UINT),
            ('CustomAttack_3', TYPE_UINT),
            ('CustomAttack_4', TYPE_UINT),
            ('NPCSoundID', TYPE_UINT),
            ('LoopSoundID', TYPE_UINT),
            ('CreatureImpactType', TYPE_UINT),
            ('SoundJumpStartID', TYPE_UINT),
            ('SoundJumpEndID', TYPE_UINT),
            ('SoundPetAttackID', TYPE_UINT),
            ('SoundPetOrderID', TYPE_UINT),
            ('SoundPetDismissID', TYPE_UINT),
            ('FidgetDelaySecondsMin', TYPE_FLOAT),
            ('FidgetDelaySecondsMax', TYPE_FLOAT),
            ('BirthSoundID', TYPE_UINT),
            ('SpellCastDirectedSoundID', TYPE_UINT),
            ('SubmergeSoundID', TYPE_UINT),
            ('SubmergedSoundID', TYPE_UINT),
            ('CreatureSoundDataIDPet', TYPE_UINT),
        ],
                
        # ========================================
        # F
        # ========================================
        'FootstepTerrainLookup': [
            ('ID', TYPE_UINT),
            ('CreatureFootstepID', TYPE_UINT),
            ('TerrainSoundID', TYPE_UINT),
            ('SoundID', TYPE_UINT),
            ('SoundIDSplash', TYPE_UINT),
        ],
        
        # ========================================
        # G
        # ========================================
        'GameObjectDisplayInfo': [
            ('ID', TYPE_UINT),
            ('ModelName', TYPE_STRING),
            ('Sound_1', TYPE_UINT),
            ('Sound_2', TYPE_UINT),
            ('Sound_3', TYPE_UINT),
            ('Sound_4', TYPE_UINT),
            ('Sound_5', TYPE_UINT),
            ('Sound_6', TYPE_UINT),
            ('Sound_7', TYPE_UINT),
            ('Sound_8', TYPE_UINT),
            ('Sound_9', TYPE_UINT),
            ('Sound_10', TYPE_UINT),
            ('GeoBoxMinX', TYPE_FLOAT),
            ('GeoBoxMinY', TYPE_FLOAT),
            ('GeoBoxMinZ', TYPE_FLOAT),
            ('GeoBoxMaxX', TYPE_FLOAT),
            ('GeoBoxMaxY', TYPE_FLOAT),
            ('GeoBoxMaxZ', TYPE_FLOAT),
            ('ObjectEffectPackageID', TYPE_UINT),
        ],
        
        # ========================================
        # N
        # ========================================
        'NPCSounds': [
            ('ID', TYPE_UINT),
            ('SoundID_1', TYPE_UINT),
            ('SoundID_2', TYPE_UINT),
            ('SoundID_3', TYPE_UINT),
            ('SoundID_4', TYPE_UINT),
        ],
        
        # ========================================
        # O
        # ========================================
        'ObjectEffect': [
            ('ID', TYPE_UINT),
            ('Name', TYPE_STRING),
            ('ObjectEffectGroupID', TYPE_UINT),
            ('TriggerType', TYPE_UINT),
            ('EventType', TYPE_UINT),
            ('EffectRecType', TYPE_UINT),
            ('EffectRecID', TYPE_UINT),
            ('Attachment', TYPE_UINT),
            ('OffsetX', TYPE_FLOAT),
            ('OffsetY', TYPE_FLOAT),
            ('OffsetZ', TYPE_FLOAT),
            ('ObjectEffectModifierID', TYPE_UINT),
        ],
        
        'ObjectEffectGroup': [
            ('ID', TYPE_UINT),
            ('Name', TYPE_STRING),
        ],
        
        'ObjectEffectModifier': [
            ('ID', TYPE_UINT),
            ('InputType', TYPE_UINT),
            ('MapType', TYPE_UINT),
            ('OutputID', TYPE_UINT),
            ('Param_1', TYPE_FLOAT),
            ('Param_2', TYPE_FLOAT),
            ('Param_3', TYPE_FLOAT),
            ('Param_4', TYPE_FLOAT),
        ],
        
        'ObjectEffectPackage': [
            ('ID', TYPE_UINT),
            ('Name', TYPE_STRING),
        ],
        
        'ObjectEffectPackageElem': [
            ('ID', TYPE_UINT),
            ('ObjectEffectPackageID', TYPE_UINT),
            ('ObjectEffectGroupID', TYPE_UINT),
            ('StateType', TYPE_UINT),
        ],
        
        # ========================================
        # P
        # ========================================
        #RGB1 RGB2 RGB3 ? or 0xAARRGGBB ?
        'ParticleColor': [
            ('ID', TYPE_UINT),
            ('Start_1', TYPE_INT),
            ('Start_2', TYPE_INT),
            ('Start_3', TYPE_INT),
            ('Mid_1', TYPE_INT),
            ('Mid_2', TYPE_INT),
            ('Mid_3', TYPE_INT),
            ('End_1', TYPE_INT),
            ('End_2', TYPE_INT),
            ('End_3', TYPE_INT),
        ],
        
        # ========================================
        # S
        # ========================================
        'SoundAmbience': [
            ('ID', TYPE_UINT),
            ('AmbienceID_0', TYPE_UINT), #day
            ('AmbienceID_1', TYPE_UINT), #night
        ],
        
        'SoundEmitters': [
            ('ID', TYPE_UINT),
            ('PositionX', TYPE_FLOAT),
            ('PositionY', TYPE_FLOAT),
            ('PositionZ', TYPE_FLOAT),
            ('DirectionX', TYPE_FLOAT),
            ('DirectionY', TYPE_FLOAT),
            ('DirectionZ', TYPE_FLOAT),
            ('SoundEntriesID', TYPE_UINT),
            ('MapID', TYPE_UINT),
            ('Name', TYPE_STRING),
        ],
        
        'SoundEntries': [
            ('ID', TYPE_UINT),
            ('SoundType', TYPE_UINT),
            ('Name', TYPE_STRING),
            ('File_1', TYPE_STRING),
            ('File_2', TYPE_STRING),
            ('File_3', TYPE_STRING),
            ('File_4', TYPE_STRING),
            ('File_5', TYPE_STRING),
            ('File_6', TYPE_STRING),
            ('File_7', TYPE_STRING),
            ('File_8', TYPE_STRING),
            ('File_9', TYPE_STRING),
            ('File_10', TYPE_STRING),
            ('Freq_1', TYPE_UINT),
            ('Freq_2', TYPE_UINT),
            ('Freq_3', TYPE_UINT),
            ('Freq_4', TYPE_UINT),
            ('Freq_5', TYPE_UINT),
            ('Freq_6', TYPE_UINT),
            ('Freq_7', TYPE_UINT),
            ('Freq_8', TYPE_UINT),
            ('Freq_9', TYPE_UINT),
            ('Freq_10', TYPE_UINT),
            ('DirectoryBase', TYPE_STRING),
            ('VolumeFloat', TYPE_FLOAT),
            ('Flags', TYPE_UINT),
            ('MinDistance', TYPE_FLOAT),
            ('DistanceCutoff', TYPE_FLOAT),
            ('EAXDef', TYPE_UINT),
            ('SoundEntriesAdvancedID', TYPE_UINT),
        ],
        
        'SoundEntriesAdvanced': [
            ('ID', TYPE_UINT),
            ('SoundEntryID', TYPE_UINT),
            ('InnerRadius2D', TYPE_FLOAT),
            ('TimeA', TYPE_UINT),
            ('TimeB', TYPE_UINT),
            ('TimeC', TYPE_UINT),
            ('TimeD', TYPE_UINT),
            ('RandomOffsetRange', TYPE_UINT),
            ('Usage', TYPE_UINT),
            ('TimeIntervalMin', TYPE_UINT),
            ('TimeIntervalMax', TYPE_UINT),
            ('VolumeSliderCategory', TYPE_UINT),
            ('DuckToSFX', TYPE_FLOAT),
            ('DuckToMusic', TYPE_FLOAT),
            ('DuckToAmbience', TYPE_FLOAT),
            ('InnerRadiusOfInfluence', TYPE_FLOAT),
            ('OuterRadiusOfInfluence', TYPE_FLOAT),
            ('TimeToDuck', TYPE_UINT),
            ('TimeToUnduck', TYPE_UINT),
            ('InsideAngle', TYPE_FLOAT),
            ('OutsideAngle', TYPE_FLOAT),
            ('OutsideVolume', TYPE_FLOAT),
            ('OuterRadius2D', TYPE_FLOAT),
            ('Name', TYPE_STRING),
        ],
        
        'SoundFilter': [
            ('ID', TYPE_UINT),
            ('Name', TYPE_STRING),
        ],
        
        'SoundFilterElem': [
            ('ID', TYPE_UINT),
            ('SoundFilterID', TYPE_UINT),
            ('OrderIndex', TYPE_UINT),
            ('FilterType', TYPE_UINT),
            ('Params_0', TYPE_FLOAT),
            ('Params_1', TYPE_FLOAT),
            ('Params_2', TYPE_FLOAT),
            ('Params_3', TYPE_FLOAT),
            ('Params_4', TYPE_FLOAT),
            ('Params_5', TYPE_FLOAT),
            ('Params_6', TYPE_FLOAT),
            ('Params_7', TYPE_FLOAT),
            ('Params_8', TYPE_FLOAT),
        ],
        
        'SoundProviderPreferences': [
            ('ID', TYPE_UINT),
            ('Description', TYPE_STRING),
            ('Flags', TYPE_UINT),
            ('EAXEnvironmentSelection', TYPE_UINT),
            ('EAXDecayTime', TYPE_FLOAT),
            ('EAX2EnvironmentSize', TYPE_FLOAT),
            ('EAX2EnvironmentDiffusion', TYPE_FLOAT),
            ('EAX2Room', TYPE_INT),
            ('EAX2RoomHF', TYPE_INT),
            ('EAX2DecayHFRatio', TYPE_FLOAT),
            ('EAX2Reflections', TYPE_INT),
            ('EAX2ReflectionsDelay', TYPE_FLOAT),
            ('EAX2Reverb', TYPE_INT),
            ('EAX2ReverbDelay', TYPE_FLOAT),
            ('EAX2RoomRolloff', TYPE_FLOAT),
            ('EAX2AirAbsorption', TYPE_FLOAT),
            ('EAX3RoomLF', TYPE_UINT),
            ('EAX3DecayLFRatio', TYPE_FLOAT),
            ('EAX3EchoTime', TYPE_FLOAT),
            ('EAX3EchoDepth', TYPE_FLOAT),
            ('EAX3ModulationTime', TYPE_FLOAT),
            ('EAX3ModulationDepth', TYPE_FLOAT),
            ('EAX3HFReference', TYPE_FLOAT),
            ('EAX3LFReference', TYPE_FLOAT),
        ],
        
        # ========================================
        # V
        # ========================================
        'VocalUISounds': [
            ('ID', TYPE_UINT),
            ('VocalUIEnum', TYPE_UINT),
            ('RaceID', TYPE_UINT),
            ('NormalSoundID_1', TYPE_INT), #male
            ('NormalSoundID_2', TYPE_INT), #female
            ('PissedSoundID_1', TYPE_INT), #male
            ('PissedSoundID_2', TYPE_INT), #female
        ],
        
        # ========================================
        # W
        # ========================================
        'WeaponImpactSounds': [
            ('ID', TYPE_UINT),
            ('WeaponSubClassID', TYPE_UINT),
            ('ParrySoundType', TYPE_UINT),
            ('ImpactSoundID_1', TYPE_UINT),
            ('ImpactSoundID_2', TYPE_UINT),
            ('ImpactSoundID_3', TYPE_UINT),
            ('ImpactSoundID_4', TYPE_UINT),
            ('ImpactSoundID_5', TYPE_UINT),
            ('ImpactSoundID_6', TYPE_UINT),
            ('ImpactSoundID_7', TYPE_UINT),
            ('ImpactSoundID_8', TYPE_UINT),
            ('ImpactSoundID_9', TYPE_UINT),
            ('ImpactSoundID_10', TYPE_UINT),
            ('CritImpactSoundID_1', TYPE_UINT),
            ('CritImpactSoundID_2', TYPE_UINT),
            ('CritImpactSoundID_3', TYPE_UINT),
            ('CritImpactSoundID_4', TYPE_UINT),
            ('CritImpactSoundID_5', TYPE_UINT),
            ('CritImpactSoundID_6', TYPE_UINT),
            ('CritImpactSoundID_7', TYPE_UINT),
            ('CritImpactSoundID_8', TYPE_UINT),
            ('CritImpactSoundID_9', TYPE_UINT),
            ('CritImpactSoundID_10', TYPE_UINT),
        ],
        
        # ========================================
        # Z
        # ========================================
        'ZoneIntroMusicTable': [
            ('ID', TYPE_UINT),
            ('Name', TYPE_STRING),
            ('SoundID', TYPE_UINT),
            ('Priority', TYPE_UINT),
            ('MinDelayMinutes', TYPE_UINT),
        ],
        
        'ZoneMusic': [
            ('ID', TYPE_UINT),
            ('SetName', TYPE_STRING),
            ('SilenceIntervalMin_1', TYPE_UINT), #day
            ('SilenceIntervalMin_2', TYPE_UINT), #night
            ('SilenceIntervalMax_1', TYPE_UINT), #day
            ('SilenceIntervalMax_2', TYPE_UINT), #night
            ('Sounds_1', TYPE_UINT),             #day
            ('Sounds_2', TYPE_UINT),             #night
        ],
    }
    
    @classmethod
    def get_schema(cls, table_name: str) -> Optional[List[Tuple[str, str]]]:
        """Get schema for a table"""
        return cls.SCHEMAS.get(table_name)
    
    @classmethod
    def get_field_count(cls, table_name: str) -> int:
        """Get number of fields in schema"""
        schema = cls.get_schema(table_name)
        return len(schema) if schema else 0
    
    @classmethod
    def get_record_size(cls, table_name: str) -> int:
        """Calculate record size in bytes"""
        schema = cls.get_schema(table_name)
        if not schema:
            return 0
        
        size = 0
        for field_name, field_type in schema:
            if field_type in [TYPE_INT, TYPE_UINT, TYPE_FLOAT, TYPE_STRING]:
                size += 4
            elif field_type == TYPE_LOCSTRING:
                size += 68  # 16 locale strings (4 bytes each) + flags (4 bytes)
        
        return size


class StringBlock:
    """Manages DBC string block with deduplication"""
    
    def __init__(self):
        self.strings = {}  # string -> offset
        self.block = bytearray([0])  # Start with null terminator
        self.offset = 1
    
    def add_string(self, s: str) -> int:
        """Add string and return its offset"""
        if not s:
            return 0
        
        # Check if string already exists
        if s in self.strings:
            return self.strings[s]
        
        # Add new string
        offset = self.offset
        self.strings[s] = offset
        
        # Encode and append to block
        encoded = s.encode('utf-8') + b'\x00'
        self.block.extend(encoded)
        self.offset += len(encoded)
        
        return offset
    
    def get_block(self) -> bytes:
        """Get the complete string block"""
        return bytes(self.block)
    
    def get_size(self) -> int:
        """Get string block size"""
        return len(self.block)


class DBCReader:
    """Reads binary DBC files"""
    
    def __init__(self, filepath: str, schema: List[Tuple[str, str]]):
        self.filepath = filepath
        self.schema = schema
        self.records = []
        self.string_block = b''
        self.header = {}
    
    def read(self) -> bool:
        """Read DBC file"""
        if not os.path.exists(self.filepath):
            return False
        
        try:
            with open(self.filepath, 'rb') as f:
                # Read header
                magic = f.read(4)
                if magic != DBC_MAGIC:
                    print(f"ERROR: Invalid DBC magic in {self.filepath}")
                    return False
                
                record_count = struct.unpack('<I', f.read(4))[0]
                field_count = struct.unpack('<I', f.read(4))[0]
                record_size = struct.unpack('<I', f.read(4))[0]
                string_block_size = struct.unpack('<I', f.read(4))[0]
                
                self.header = {
                    'record_count': record_count,
                    'field_count': field_count,
                    'record_size': record_size,
                    'string_block_size': string_block_size
                }
                
                # Validate record size matches schema
                expected_size = self._calculate_record_size()
                if record_size != expected_size:
                    print(f"WARNING: Record size mismatch in {os.path.basename(self.filepath)}")
                    print(f"  Expected: {expected_size} bytes (from schema)")
                    print(f"  Actual:   {record_size} bytes (from DBC)")
                    print(f"  This DBC may have a different structure than expected.")
                    print(f"  Skipping this file to avoid corruption.")
                    return False
                
                # Read records
                records_data = f.read(record_count * record_size)
                
                # Read string block
                self.string_block = f.read(string_block_size)
                
                # Parse records
                self._parse_records(records_data, record_count, record_size)
                
                return True
                
        except Exception as e:
            print(f"ERROR reading {self.filepath}: {e}")
            return False
    
    def _calculate_record_size(self) -> int:
        """Calculate expected record size from schema"""
        size = 0
        for field_name, field_type in self.schema:
            if field_type in [TYPE_INT, TYPE_UINT, TYPE_FLOAT, TYPE_STRING]:
                size += 4
            elif field_type == TYPE_LOCSTRING:
                size += 68  # 16 locale strings (4 bytes each) + flags (4 bytes)
        return size
    
    def _parse_records(self, data: bytes, count: int, size: int):
        """Parse binary records into dictionaries"""
        for i in range(count):
            offset = i * size
            record_data = data[offset:offset + size]
            record = self._parse_record(record_data)
            if record:
                self.records.append(record)
    
    def _parse_record(self, data: bytes) -> Optional[Dict[str, Any]]:
        """Parse a single record"""
        record = {}
        offset = 0
        
        try:
            for field_name, field_type in self.schema:
                if field_type == TYPE_INT:
                    value = struct.unpack('<i', data[offset:offset+4])[0]
                    offset += 4
                elif field_type == TYPE_UINT:
                    value = struct.unpack('<I', data[offset:offset+4])[0]
                    offset += 4
                elif field_type == TYPE_FLOAT:
                    value = struct.unpack('<f', data[offset:offset+4])[0]
                    offset += 4
                elif field_type == TYPE_STRING:
                    str_offset = struct.unpack('<I', data[offset:offset+4])[0]
                    value = self._read_string(str_offset)
                    offset += 4
                elif field_type == TYPE_LOCSTRING:
                    # Read 16 locale strings + flags (17 * 4 bytes)
                    # For now, just read the first locale
                    str_offset = struct.unpack('<I', data[offset:offset+4])[0]
                    value = self._read_string(str_offset)
                    offset += 68  # Skip all locale data
                else:
                    value = 0
                    offset += 4
                
                record[field_name] = value
            
            return record
            
        except Exception as e:
            print(f"ERROR parsing record: {e}")
            return None
    
    def _read_string(self, offset: int) -> str:
        """Read null-terminated string from string block"""
        if offset == 0 or offset >= len(self.string_block):
            return ''
        
        end = self.string_block.find(b'\x00', offset)
        if end == -1:
            end = len(self.string_block)
        
        try:
            return self.string_block[offset:end].decode('utf-8')
        except:
            return ''
    
    def get_records_by_id(self) -> Dict[int, Dict[str, Any]]:
        """Return records indexed by ID"""
        return {record['ID']: record for record in self.records}


class DBCWriter:
    """Writes binary DBC files"""
    
    def __init__(self, schema: List[Tuple[str, str]]):
        self.schema = schema
        self.string_block = StringBlock()
    
    def write(self, filepath: str, records: List[Dict[str, Any]]) -> bool:
        """Write records to DBC file"""
        try:
            # Calculate sizes
            record_count = len(records)
            field_count = len(self.schema)
            record_size = DBCSchema.get_record_size(
                os.path.splitext(os.path.basename(filepath))[0]
            )
            
            # Build records and string block
            records_data = bytearray()
            failed_count = 0
            
            for record in records:
                record_bytes = self._build_record(record)
                if record_bytes:
                    records_data.extend(record_bytes)
                else:
                    failed_count += 1
                    record_count -= 1  # Reduce count for failed records
            
            if failed_count > 0:
                print(f"  WARNING: Skipped {failed_count} record(s) due to errors")
            
            if record_count == 0:
                print(f"  ERROR: No valid records to write")
                return False
            
            string_block_data = self.string_block.get_block()
            string_block_size = len(string_block_data)
            
            # Write file
            with open(filepath, 'wb') as f:
                # Write header
                f.write(DBC_MAGIC)
                f.write(struct.pack('<I', record_count))
                f.write(struct.pack('<I', field_count))
                f.write(struct.pack('<I', record_size))
                f.write(struct.pack('<I', string_block_size))
                
                # Write records
                f.write(records_data)
                
                # Write string block
                f.write(string_block_data)
            
            return True
            
        except Exception as e:
            print(f"ERROR writing {filepath}: {e}")
            return False
    
    def _build_record(self, record: Dict[str, Any]) -> Optional[bytes]:
        """Build binary data for a single record"""
        data = bytearray()
        
        try:
            for field_name, field_type in self.schema:
                value = record.get(field_name, 0 if field_type != TYPE_STRING else '')
                
                if field_type == TYPE_INT:
                    # Signed integer (-2147483648 to 2147483647)
                    int_val = int(value) if value != '' and value != 'NULL' else 0
                    # Clamp to int32 range
                    int_val = max(-2147483648, min(2147483647, int_val))
                    data.extend(struct.pack('<i', int_val))
                    
                elif field_type == TYPE_UINT:
                    # Unsigned integer (0 to 4294967295)
                    if value == '' or value == 'NULL':
                        uint_val = 0
                    else:
                        try:
                            uint_val = int(value)
                            # Handle negative values (treat as 0)
                            if uint_val < 0:
                                uint_val = 0
                            # Clamp to uint32 range
                            elif uint_val > 4294967295:
                                uint_val = 4294967295
                        except (ValueError, TypeError):
                            uint_val = 0
                    data.extend(struct.pack('<I', uint_val))
                    
                elif field_type == TYPE_FLOAT:
                    # Handle WDBX format (comma as decimal separator)
                    if isinstance(value, str):
                        value = value.replace(',', '.')
                    try:
                        float_val = float(value) if value != '' and value != 'NULL' else 0.0
                    except (ValueError, TypeError):
                        float_val = 0.0
                    data.extend(struct.pack('<f', float_val))
                    
                elif field_type == TYPE_STRING:
                    str_val = str(value) if value and value != 'NULL' else ''
                    str_offset = self.string_block.add_string(str_val)
                    data.extend(struct.pack('<I', str_offset))
                    
                elif field_type == TYPE_LOCSTRING:
                    # Write first locale string, rest as 0
                    str_val = str(value) if value and value != 'NULL' else ''
                    str_offset = self.string_block.add_string(str_val)
                    data.extend(struct.pack('<I', str_offset))
                    # Add 16 more zeros for other locales + flags
                    data.extend(b'\x00' * 64)
            
            return bytes(data)
            
        except Exception as e:
            print(f"ERROR building record {record.get('ID', '?')} field '{field_name}': {e}")
            print(f"  Value: {value}, Type: {field_type}")
            return None


class CSVReader:
    """Reads CSV files (both standard and WDBX format)"""
    
    @staticmethod
    def read(filepath: str) -> List[Dict[str, Any]]:
        """Read CSV file and return list of records"""
        records = []
        
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    # Clean up row data
                    cleaned_row = {}
                    for key, value in row.items():
                        # Remove quotes if present (WDBX format)
                        if isinstance(value, str):
                            value = value.strip().strip('"')
                        cleaned_row[key] = value
                    records.append(cleaned_row)
            
            return records
            
        except Exception as e:
            print(f"ERROR reading CSV {filepath}: {e}")
            return []


class DBCMerger:
    """Merges CSV data into existing DBC files"""
    
    def __init__(self):
        self.stats = {
            'added': 0,
            'updated': 0,
            'unchanged': 0,
            'errors': 0,
            'skipped': 0
        }
    
    def merge(self, table_name: str, dbc_path: str, csv_path: str) -> bool:
        """Merge CSV data into DBC file"""
        print(f"\nProcessing: {table_name}")
        print("=" * 60)
        
        # Get schema
        schema = DBCSchema.get_schema(table_name)
        if not schema:
            print(f"ERROR: No schema defined for {table_name}")
            self.stats['errors'] += 1
            return False
        
        # Read existing DBC
        existing_records = {}
        dbc_exists = os.path.exists(dbc_path)
        
        if dbc_exists:
            print(f"Reading existing DBC: {dbc_path}")
            reader = DBCReader(dbc_path, schema)
            if reader.read():
                existing_records = reader.get_records_by_id()
                print(f"  Loaded {len(existing_records)} existing records")
            else:
                print(f"WARNING: Could not read existing DBC")
        else:
            print(f"No existing DBC found, will create new file")
        
        # Read CSV data
        print(f"Reading CSV: {csv_path}")
        csv_records = CSVReader.read(csv_path)
        if not csv_records:
            print(f"WARNING: No records in CSV file")
            return False
        
        print(f"  Loaded {len(csv_records)} CSV records")
        
        # Merge data
        merged_records = dict(existing_records)  # Start with existing
        
        added = 0
        updated = 0
        
        for csv_record in csv_records:
            record_id = int(csv_record.get('ID', 0))
            if record_id == 0:
                continue
            
            if record_id in merged_records:
                # Update existing record
                merged_records[record_id] = csv_record
                updated += 1
            else:
                # Add new record
                merged_records[record_id] = csv_record
                added += 1
        
        # Sort records by ID
        sorted_records = [merged_records[k] for k in sorted(merged_records.keys())]
        
        # Create backup if DBC exists
        if dbc_exists:
            backup_path = dbc_path + '.bak'
            try:
                import shutil
                shutil.copy2(dbc_path, backup_path)
                print(f"  Created backup: {backup_path}")
            except:
                print(f"  WARNING: Could not create backup")
        
        # Write merged DBC
        print(f"Writing updated DBC...")
        writer = DBCWriter(schema)
        if writer.write(dbc_path, sorted_records):
            print(f"  ✓ Successfully wrote {len(sorted_records)} records")
            print(f"  Added: {added}, Updated: {updated}")
            self.stats['added'] += added
            self.stats['updated'] += updated
            return True
        else:
            print(f"  ERROR: Failed to write DBC")
            self.stats['errors'] += 1
            return False
    
    def print_summary(self):
        """Print merge summary"""
        print("\n" + "=" * 60)
        print("MERGE SUMMARY")
        print("=" * 60)
        print(f"Records added:   {self.stats['added']}")
        print(f"Records updated: {self.stats['updated']}")
        print(f"Records skipped: {self.stats['skipped']}")
        print(f"Errors:          {self.stats['errors']}")
        print("=" * 60)


def find_csv_file(table_name: str) -> Optional[str]:
    """Find CSV file for table in source directories"""
    csv_filename = f"{table_name}.csv"
    
    for source_dir in CSV_SOURCES:
        csv_path = os.path.join(source_dir, csv_filename)
        if os.path.exists(csv_path):
            return csv_path
    
    return None


def main():
    print("=" * 60)
    print("CSV to DBC Converter - WoW 3.3.5a (WotLK)")
    print("=" * 60)
    
    # Check DBC directory
    if not os.path.exists(DBC_DIR):
        print(f"\nCreating DBC directory: {DBC_DIR}")
        os.makedirs(DBC_DIR, exist_ok=True)
        print(f"Please place your WotLK DBC files in: {DBC_DIR}/")
        return
    
    # Check which CSV sources are available
    available_sources = []
    source_table_counts = {}
    
    for source_dir in CSV_SOURCES:
        if os.path.exists(source_dir):
            # Count CSV files in this directory
            csv_count = 0
            for table_name in DBCSchema.SCHEMAS.keys():
                csv_path = os.path.join(source_dir, f"{table_name}.csv")
                if os.path.exists(csv_path):
                    csv_count += 1
            
            if csv_count > 0:
                available_sources.append(source_dir)
                source_table_counts[source_dir] = csv_count
    
    if not available_sources:
        print("\nNo CSV files found in:")
        for source in CSV_SOURCES:
            print(f"  - {source}/")
        print("\nPlease run DB2_to_DBC.py or DB2_to_DBC_Filtered.py first.")
        return
    
    # If only one source available, use it automatically
    if len(available_sources) == 1:
        selected_source = available_sources[0]
        print(f"\nFound CSV source: {selected_source}/")
        print(f"  Contains {source_table_counts[selected_source]} table(s)")
    else:
        # Ask user to choose between sources
        print("\nMultiple CSV sources found:")
        print()
        for i, source_dir in enumerate(available_sources, 1):
            print(f"  [{i}] {source_dir}/ ({source_table_counts[source_dir]} table(s))")
        print()
        
        # Get user choice
        while True:
            try:
                choice_input = input(f"Select CSV source [1-{len(available_sources)}]: ").strip()
                choice = int(choice_input)
                if 1 <= choice <= len(available_sources):
                    selected_source = available_sources[choice - 1]
                    break
                else:
                    print(f"Please enter a number between 1 and {len(available_sources)}")
            except ValueError:
                print("Please enter a valid number")
            except KeyboardInterrupt:
                print("\nCancelled.")
                return
    
    # Find tables to process from selected source
    tables_to_process = []
    
    print(f"\nScanning CSV files in: {selected_source}/")
    for table_name in DBCSchema.SCHEMAS.keys():
        csv_path = os.path.join(selected_source, f"{table_name}.csv")
        if os.path.exists(csv_path):
            dbc_path = os.path.join(DBC_DIR, f"{table_name}.dbc")
            tables_to_process.append((table_name, dbc_path, csv_path))
            print(f"  Found: {table_name}.csv")
    
    if not tables_to_process:
        print(f"\nNo valid CSV files found in {selected_source}/")
        return
    
    print(f"\nFound {len(tables_to_process)} table(s) to process")
    
    # Confirm processing
    print("\nThis will UPDATE existing DBC files with new data from CSV files.")
    print("Backups will be created as .dbc.bak")
    response = input("\nProceed? (y/n): ").strip().lower()
    
    if response not in ['y', 'yes']:
        print("Cancelled.")
        return
    
    # Process tables
    merger = DBCMerger()
    
    for table_name, dbc_path, csv_path in tables_to_process:
        merger.merge(table_name, dbc_path, csv_path)
    
    # Print summary
    merger.print_summary()
    
    print("\nDone! Your updated DBC files are in:")
    print(f"  {DBC_DIR}/")
    print("\nCopy the DBFilesClient folder to your WoW Data directory.")


if __name__ == "__main__":
    main()